# Generated by Django 5.2 on 2025-07-23 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-date_created', '-id'], 'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_created', '-id'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-date_created', '-id'], 'verbose_name': 'Support Ticket', 'verbose_name_plural': 'Support Tickets'},
        ),
    ]
