# Generated by Django 5.1.1 on 2025-07-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0002_comment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
