# Generated by Django 5.2 on 2025-07-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='Email Notifications'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='whatsapp_notifications',
            field=models.BooleanField(default=False, verbose_name='WhatsApp Notifications'),
        ),
    ]
