# Generated by Django 5.2 on 2025-07-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of attendance', verbose_name='Date')),
                ('check_in_time', models.DateTimeField(help_text='Time when member checked in', verbose_name='Check-in Time')),
                ('verification_method', models.CharField(default='Biometric', help_text='Method used to verify attendance', max_length=20, verbose_name='Verification Method')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ['-date', '-check_in_time'],
            },
        ),
    ]
