# Generated by Django 5.1.1 on 2025-08-02 11:40

import apps.Attendance.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Member', '0002_member_pin_member_pin_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of attendance', verbose_name='Date')),
                ('check_in_time', models.DateTimeField(help_text='Time when member checked in', verbose_name='Check-in Time')),
                ('verification_method', models.CharField(default='Biometric', help_text='Method used to verify attendance', max_length=20, verbose_name='Verification Method')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='Member.member', verbose_name='Member')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ['-date', '-check_in_time'],
                'unique_together': {('member', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CheckInPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Photo taken during check-in for security verification. Auto-deleted after 24 hours.', upload_to=apps.Attendance.models.checkin_photo_path, verbose_name='Check-in Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='Attendance.attendance', verbose_name='Attendance')),
            ],
            options={
                'verbose_name': 'Check-in Photo',
                'verbose_name_plural': 'Check-in Photos',
                'ordering': ['-created_at'],
            },
        ),
    ]
