[build]
  command = "npm run build"
  publish = "dist"  # This matches your Vite build output directory

# For single-page applications (like React)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (if needed)
[build.environment]
  NODE_VERSION = "16"  # Or your preferred version

# Optional build settings for optimization
[build.processing]
  skip_processing = true