# Generated by Django 5.2 on 2025-04-22 10:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('member', 'Member'), ('trainer', 'Trainer'), ('admin', 'Admin')], default='member', max_length=10, verbose_name='User Role')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='Email Address')),
                ('username', models.CharField(blank=True, help_text='Optional. 4-150 characters.', max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Username')),
                ('first_name', models.CharField(help_text='Required. 150 characters or fewer.', max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Required. 150 characters or fewer.', max_length=150, verbose_name='Last Name')),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
                ('athlete_id', models.CharField(help_text='Unique identifier for the athlete', max_length=20, unique=True, verbose_name='Athlete ID')),
                ('biometric_data', models.TextField(blank=True, help_text='Base64 encoded biometric template', null=True, verbose_name='Biometric Data')),
                ('biometric_registered', models.BooleanField(default=False, help_text='Whether member has registered their biometrics', verbose_name='Biometric Registered')),
                ('first_name', models.CharField(default='John', help_text='Athlete first name', max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(default='Doe', help_text='Athlete last name', max_length=150, verbose_name='Last Name')),
                ('monthly_fee', models.DecimalField(decimal_places=2, help_text='Monthly membership fee in local currency', max_digits=8, verbose_name='Monthly Fee')),
                ('membership_type', models.CharField(choices=[('fitness', 'Fitness'), ('gym', 'Gym')], default='fitness', max_length=10, verbose_name='Membership Type')),
                ('start_date', models.DateField(help_text='Date when membership begins', verbose_name='Start Date')),
                ('expiry_date', models.DateField(help_text='Date when membership expires', verbose_name='Expiry Date')),
                ('box_number', models.CharField(blank=True, help_text='Locker or box number assigned to member', max_length=20, null=True, verbose_name='Box Number')),
                ('time_slot', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='morning', help_text='Preferred workout time', max_length=10, verbose_name='Time Slot')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('specialization', models.CharField(choices=[('fitness', 'Fitness'), ('yoga', 'Yoga'), ('cardio', 'Cardio'), ('strength', 'Strength Training'), ('nutrition', 'Nutrition')], default='fitness', max_length=20)),
                ('start_date', models.DateField(default='2023-06-20')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('fitness', 'Fitness'), ('yoga', 'Yoga'), ('cardio', 'Cardio'), ('strength', 'Strength Training'), ('nutrition', 'Nutrition')], max_length=20)),
                ('datetime', models.DateTimeField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('capacity', models.IntegerField(default=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='users.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of attendance', verbose_name='Date')),
                ('check_in_time', models.DateTimeField(help_text='Time when member checked in', verbose_name='Check-in Time')),
                ('verification_method', models.CharField(default='Biometric', help_text='Method used to verify attendance', max_length=20, verbose_name='Verification Method')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='users.member', verbose_name='Member')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ['-date', '-check_in_time'],
                'unique_together': {('member', 'date')},
            },
        ),
    ]
