# Generated by Django 5.2 on 2025-06-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, help_text='Member phone number', max_length=20, null=True, verbose_name='Phone Number'),
        ),
    ]
