# Generated by Django 5.2 on 2025-04-15 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, help_text='Optional. 4-150 characters. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Username'),
        ),
    ]
