# Generated by Django 5.2 on 2025-04-20 08:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceHistory',
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', '-check_in_time']},
        ),
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_member_attendance_per_day',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='member',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='notes',
        ),
        migrations.AddField(
            model_name='attendance',
            name='athlete_id',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='attendance',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='time_slot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
