# Generated by Django 5.2 on 2025-06-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='notified_expired',
            field=models.BooleanField(default=False),
        ),
    ]
