# Generated by Django 5.2 on 2025-04-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_first_name_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='first_name',
            field=models.CharField(default='John', help_text='Athlete first name', max_length=150, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='member',
            name='last_name',
            field=models.CharField(default='Doe', help_text='Athlete last name', max_length=150, verbose_name='Last Name'),
        ),
    ]
