# Generated by Django 5.2 on 2025-04-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_webauthncredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webauthncredential',
            name='rp_id',
            field=models.CharField(default='localhost', max_length=255),
        ),
    ]
