# Generated by Django 5.2 on 2025-06-15 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_member_notified_expired'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(blank=True, max_length=100, null=True)),
                ('tuesday', models.CharField(blank=True, max_length=100, null=True)),
                ('wednesday', models.CharField(blank=True, max_length=100, null=True)),
                ('thursday', models.CharField(blank=True, max_length=100, null=True)),
                ('friday', models.CharField(blank=True, max_length=100, null=True)),
                ('saturday', models.CharField(blank=True, max_length=100, null=True)),
                ('sunday', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_schedule', to='users.member')),
            ],
        ),
    ]
