# Generated by Django 5.2 on 2025-04-17 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(verbose_name='Check-in Time')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='Check-out Time')),
                ('date', models.DateField(verbose_name='Attendance Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='users.member', verbose_name='Member')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ['-date', '-check_in_time'],
                'constraints': [models.UniqueConstraint(fields=('member', 'date'), name='unique_member_attendance_per_day')],
            },
        ),
    ]
