# Generated by Django 5.2 on 2025-04-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='box_number',
            field=models.CharField(blank=True, help_text='Locker or box number assigned to member', max_length=20, null=True, verbose_name='Box Number'),
        ),
        migrations.AddField(
            model_name='member',
            name='time_slot',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='morning', help_text='Preferred workout time', max_length=10, verbose_name='Time Slot'),
        ),
    ]
