# Generated by Django 5.2 on 2025-04-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_member_box_number_member_time_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_id', models.CharField(max_length=50)),
                ('member_name', models.CharField(max_length=100)),
                ('box_number', models.CharField(blank=True, max_length=10, null=True)),
                ('time_slot', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField()),
                ('check_in_time', models.DateTimeField()),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='completed', max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='users_atten_date_15c0f3_idx'), models.Index(fields=['athlete_id'], name='users_atten_athlete_2f01b4_idx')],
            },
        ),
    ]
