# Generated by Django 5.2 on 2025-04-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_attendancehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('training_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Personal Training', 'Personal Training'), ('Group Fitness', 'Group Fitness'), ('Yoga', 'Yoga'), ('Pilates', 'Pilates'), ('Crossfit', 'Crossfit'), ('Boxing', 'Boxing'), ('Cardio', 'Cardio'), ('Strength', 'Strength'), ('Flexibility', 'Flexibility'), ('HIIT', 'HIIT')], max_length=50)),
                ('trainer', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('capacity', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
