# Generated by Django 5.2 on 2025-07-28 05:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
                ('is_active', models.BooleanField(default=True)),
                ('athlete_id', models.CharField(help_text='Unique identifier for the athlete', max_length=20, unique=True, verbose_name='Athlete ID')),
                ('biometric_hash', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('biometric_registered', models.BooleanField(default=False)),
                ('first_name', models.CharField(default='John', help_text='Athlete first name', max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(default='Doe', help_text='Athlete last name', max_length=150, verbose_name='Last Name')),
                ('monthly_fee', models.DecimalField(decimal_places=2, help_text='Monthly membership fee in local currency', max_digits=8, verbose_name='Monthly Fee')),
                ('membership_type', models.CharField(choices=[('fitness', 'Fitness'), ('gym', 'Gym')], default='fitness', max_length=10, verbose_name='Membership Type')),
                ('phone', models.CharField(blank=True, help_text='Member phone number', max_length=20, null=True, verbose_name='Phone Number')),
                ('start_date', models.DateField(help_text='Date when membership begins', verbose_name='Start Date')),
                ('expiry_date', models.DateField(help_text='Date when membership expires', verbose_name='Expiry Date')),
                ('box_number', models.CharField(blank=True, help_text='Locker or box number assigned to member', max_length=20, null=True, verbose_name='Box Number')),
                ('time_slot', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='morning', help_text='Preferred workout time', max_length=10, verbose_name='Time Slot')),
                ('notified_expired', models.BooleanField(default=False)),
                ('delete_requested', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('specialization', models.CharField(choices=[('fitness', 'Fitness'), ('yoga', 'Yoga'), ('cardio', 'Cardio'), ('strength', 'Strength Training'), ('nutrition', 'Nutrition')], default='fitness', max_length=100)),
                ('start_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='trainer_images/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('member_name', models.CharField(max_length=255, null=True)),
                ('paid_on', models.DateField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Member.member')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('fitness', 'Fitness'), ('yoga', 'Yoga'), ('cardio', 'Cardio'), ('strength', 'Strength Training'), ('nutrition', 'Nutrition')], max_length=20)),
                ('datetime', models.DateTimeField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('capacity', models.IntegerField(default=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='training_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='Member.trainer')),
            ],
        ),
    ]
