# Generated by Django 5.2 on 2025-07-22 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('fitness', 'Fitness'), ('yoga', 'Yoga'), ('cardio', 'Cardio'), ('strength', 'Strength Training'), ('nutrition', 'Nutrition')], max_length=20)),
                ('datetime', models.DateTimeField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('capacity', models.IntegerField(default=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='Member.trainer')),
            ],
        ),
    ]
