# Generated by Django 5.1.1 on 2025-08-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pin',
            field=models.CharField(blank=True, help_text='4-6 digit PIN for check-in', max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='pin_enabled',
            field=models.BooleanField(default=False, help_text='Enable PIN-based check-in for this member'),
        ),
        migrations.AddField(
            model_name='member',
            name='pin_reference_photo',
            field=models.ImageField(blank=True, help_text='Reference photo for PIN verification', null=True, upload_to='pin_photos/'),
        ),
    ]
