# Generated by Django 5.2 on 2025-07-22 13:51

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0002_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trainer_images/'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='training',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 22, 13, 51, 51, 212418, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='training_images/'),
        ),
        migrations.AddField(
            model_name='training',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='specialization',
            field=models.CharField(choices=[('fitness', 'Fitness'), ('yoga', 'Yoga'), ('cardio', 'Cardio'), ('strength', 'Strength Training'), ('nutrition', 'Nutrition')], default='fitness', max_length=100),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='start_date',
            field=models.DateField(),
        ),
    ]
