# Generated by Django 5.2 on 2025-07-22 14:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0003_trainer_created_at_trainer_image_trainer_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='user',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
